apiVersion: v2
name: uptime-kuma
description: Uptime Kuma, a self-hosted monitoring tool
type: application
version: 0.1.0
appVersion: "2"
keywords:
  - monitoring
  - uptime
  - status-page
home: https://github.com/louislam/uptime-kuma
sources:
  - https://github.com/louislam/uptime-kuma
maintainers:
  - name: santisbon
