apiVersion: v2
name: uptime-kuma
description: Helm chart for Uptime Kuma, a self-hosted monitoring tool
type: application
version: 0.1.0
appVersion: "2"
keywords:
  - monitoring
  - uptime
  - status-page
home: https://github.com/santisbon/uptime
sources:
  - https://github.com/santisbon/uptime
maintainers:
  - name: santisbon
